export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const GET_USERSBYID_REQUEST = "GET_USERSBYID_REQUEST";
export const GET_USERSBYID_SUCCESS = "GET_USERSBYID_SUCCESS";
export const GET_USERSBYID_FAILURE = "GET_USERSBYID_FAILURE";

export const CHANGEISOPEN = "CHANGEISOPEN";


export const UPDATE_USER_REQUEST = "GET_USERUPDATE_REQUEST";
export const UPDATE_USER_SUCCESS = "GET_USERUPDATE_SUCCESS";
export const UPDATE_USER_FAILURE = "GET_USERUPDATE_FAILURE";


export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";

