export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const GET_USERSBYID_REQUEST = "GET_USERSBYID_REQUEST";
export const GET_USERSBYID_SUCCESS = "GET_USERSBYID_SUCCESS";
export const GET_USERSBYID_FAILURE = "GET_USERSBYID_FAILURE";

export const CHANGEISOPEN = "CHANGEISOPEN";


export const GET_USERUPDATE_REQUEST = "GET_USERUPDATE_REQUEST";
export const GET_USERUPDATE_SUCCESS = "GET_USERUPDATE_SUCCESS";
export const GET_USERUPDATE_FAILURE = "GET_USERUPDATE_FAILURE";


